{{- if .Values.ingress.enabled }}
{{- $host := required "ต้องกรอก ingress.host" .Values.ingress.host }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ckan.name" . }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" .Release.Name) }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "ckan.name" . }}
                port:
                  number: 5000
{{- end }}
