apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ckan.name" . }}
  labels:
    {{- include "ckan.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "ต้องกรอก postgres.password" .Values.postgres.password | quote }}
  DATASTORE_READONLY_PASSWORD: {{ required "ต้องกรอก postgres.datastoreReadonlyPassword" .Values.postgres.datastoreReadonlyPassword | quote }}
  CKAN_SYSADMIN_PASSWORD: {{ required "ต้องกรอก sysadmin.password" .Values.sysadmin.password | quote }}
