apiVersion: v2
name: ckan-thai-gdc
description: CKAN Thai GDC (ckan + solr + redis) for Kubernetes / Portainer
type: application
# เพิ่มเลขนี้ทุกครั้งที่แก้ chart ไม่อย่างนั้น GitHub Actions จะไม่ publish เวอร์ชันใหม่
version: 1.0.4
appVersion: "v3.1.0"
keywords:
  - ckan
  - opendata
  - thai-gdc
